### ISSUE TITLE
New Game Mode Idea: Chrono Battle Royale

### ISSUE THREAD

**Issue by DeltaLeeds** [s0er3n/whenwasthisphototaken.com#8]
This is probably very complicated to code, so I never expect you to implement this. This is just an idea I'd like to let out here because it seems fun.

* At the starting round, people participating will become battle royale participants.
* Participants will start with a customizable amount of HP (Defaults to 100 Ig).
* Each year away from the actual guess is 1 less HP.
* Participants who forget to guess will automatically die.
* Damage multipliers increase by 1 starting from round 5 / 10....
* When someone dies or forgets to guess, the player becomes a ghost player.
* Players joining after round 1 will also become ghost players.
* Scoring will still be there just so that ghost players can still play along and get a score, thus keeping participation alive.
* Final player standing wins, placing is according to how late other player's deaths are.
* Final results will be something like
```
Congratulations AProPlayer, winner of the battle royale!
Starting HP: 100

- #1 - AProPlayer - Won with 38 HP (Score: 75008)
- #2 - AGoodPlayer - Died at round 16 (Score: 69200)
- #3 - AGoodPlayerWhoChokedEarly - Died at round 9 (Score: 71650)
- #4 - SomeOtherPlayer - Died at round 6 (Score: 57500)
- #5 - Aahhahahahaha - Died at round 5 (Score: 49800)
- #6 - Aahhahshahaha - Died at round 5 (Score: 65400)
- #7 - ProPlayerWhoForgotToGuess - Died at round 4 (Score: 69772)
- #8 - PlayerWhoJoinedLate - Score: 49800
- #9 - AnotherPlayerWhoJoinedLate - Score: 34800
- #10 - PlayerWhoGuessedOnceAndJoinedLate - Score: 4692
```

Yes, yes I know, it's similar to geoguessr's system, but hey, it's using a chat and we have a 25k scoring system too so why not?

**Comment by s0er3n** [comment]
not planned for now
